site:
  url: https://leo2h.github.io
  title: LeoZh's Studio
  start_page: PL::index.adoc
  robots: allow
asciidoc:
  extensions:
  - asciidoctor-kroki
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://github.com/leo2h/antora-ui-default/files/11199866/ui-bundle.zip
    snapshot: true

