= 基本语法

[#package-keyword]
== `package` 关键字

每个 `Go` 程序都是由包构成的。程序从 `main` 包的 `main` 函数开始运行。

[source,golang]
----
package main
----

[#import-keyword]
== `import` 关键字

按照约定，包名与导入路径的最后一个元素一致。例如，`"math/rand"` 包中的源码均以 `package rand` 语句开始。

[source,golang]
----
import "fmt"
import (     // <1>
  "time"
  "math/rand"
)
----
<1> “分组”形式的导入语

[#func-keyword]
== `func` 关键字

函数可以没有参数或接受多个参数。在本例中，`add` 接受两个 `int` 类型的参数。当连续两个或多个函数的已命名形参类型相同时，除最后一个类型以外，其它都可以省略。

函数可以返回任意数量的返回值。`swap` 函数返回了两个字符串。

`Go` 的返回值可被命名，它们会被视作定义在函数顶部的变量。返回值的名称应当具有一定的意义，它可以作为文档使用。没有参数的 return 语句返回已命名的返回值。也就是 直接 返回。直接返回语句应当仅用在下面这样的短函数中。在长的函数中它们会影响代码的可读性。

[source,golang]
----
include::example$func-keyword.go[tag=func]
----

[#if-keyword]
== `if` 关键字

在 `if` 的简短语句中声明的变量同样可以在任何对应的 `else` 块中使用。

[source,golang]
----
include::example$if-keyword.go[tag=if-1]
----

=== `if` 的简短语句

同 `for` 一样， `if` 语句可以在条件表达式前执行一个简单的语句。该语句声明的变量作用域仅在 `if` 之内。

[source,golang]
----
include::example$if-keyword.go[tag=if-2]
----

[#switch-keyword]
== `switch` 关键字

`switch` 是编写一连串 `if - else` 语句的简便方法。它运行第一个值等于条件表达式的 `case` 语句。

`Go` 的 `switch` 语句类似于 `C`、`C++`、`Java`、`JavaScript` 和 `PHP` 中的，不过 Go 只运行选定的 case，而非之后所有的 case。 实际上，Go 自动提供了在这些语言中每个 `case` 后面所需的 `break` 语句。 除非以 `fallthrough` 语句结束，否则分支会自动终止。 `Go` 的另一点重要的不同在于 `switch` 的 `case` 无需为常量，且取值不必为整数。

`switch` 的 `case` 语句从上到下顺次执行，直到匹配成功时停止。

[source,golang]
----
switch os {
case "windows":
  fmt.Println("Windows")
case "linux":
  fmt.Println("Linux")
default:
  fmt.Println("Unknown OS")
}
----

=== 没有条件的 `switch`

没有条件的 `switch` 同 `switch true` 一样。这种形式能将一长串 `if-then-else` 写得更加清晰。

[source,golang]
----
t := time.Now()
switch {
case t.Hour() < 12:
  fmt.Println("Good morning!")
case t.Hour() < 17:
  fmt.Println("Good afternoon.")
default:
  fmt.Println("Good evening.")
}
----

[#fallthrough-keyword]
=== `fallthrough` 关键字

[source,golang]
----
switch i := x + 1; i {
case 1:
  fmt.Println("case 1")
  fallthrough
case 2:
  fmt.Println("case 2")
default:
  fmt.Println("default")
}
----

[#for-keyword]
== `for` 关键字

`Go` 只有一种循环结构：`for` 循环。基本的 `for` 循环由三部分组成，它们用分号隔开：

* 初始化语句：在第一次迭代前执行
* 条件表达式：在每次迭代前求值
* 后置语句：在每次迭代的结尾执行

初始化语句通常为一句短变量声明，该变量声明仅在 `for` 语句的作用域中可见。一旦条件表达式的布尔值为 `false`，循环迭代就会终止。

[source,golang]
----
s := 0
for i := 0; i < 10; i++ {
  s += i
}
----

=== 初始化语句和后置语句是可选的

[source,golang]
----
s := 1
for ; s < 5; {
  s = s + 2
}
----

=== `for` 是 `Go` 中的 `while`

此时你可以去掉分号，因为 `C` 的 `while` 在 `Go` 中叫做 `for`。

[source,golang]
----
s := 1
for s < 5 {
  s = s + 2
}
----

=== 无限循环

如果省略循环条件，该循环就不会结束，因此无限循环可以写得很紧凑。

[source,golang]
----
for {
  // 无限循环
}
----

[#break-keyword]
=== `break` 关键字

[source,golang]
----
for i := 0; i < 10; i++ {
  if i % 2 == 0 {
    break
  }
}
----

[#continue-keyword]
=== `continue` 关键字

[source,golang]
----
for i := 0; i < 10; i++ {
  if i % 2 == 0 {
    continue
  }
}
----

[#range-keyword]
=== `range` 关键字

`for` 循环的 `range` 形式可遍历切片或映射。当使用 `for` 循环遍历切片时，每次迭代都会返回两个值。第一个值为当前元素的下标，第二个值为该下标所对应元素的一份副本。可以将下标或值赋予 `_` 来忽略它。

[source,golang]
----
var pow = []int{1, 2, 4, 8, 16, 32, 64, 128}
for i, v := range pow {
  fmt.Printf("2**%d = %d\n", i, v)
}

for _, v := range pow { // <1>
  //
}

for i, _ := range pow { // <2>
  //
}
----
<1> 若你只需要值，忽略第一个变量即可
<2> 若你只需要索引，忽略第二个变量即可

[#select-keyword]
== `select` 关键字

[source,golang]
----
----

[#defer-keyword]
== `defer` 关键字

[source,golang]
----
----

[#goto-keyword]
== `goto` 关键字

[source,golang]
----
func main() {
forever_loop:
  fmt.Println("forever loop")
  time.Sleep(1 * time.Second)
  goto forever_loop;
}
----
