= 基础语法

== &sect; Hello World

.Example 1
[source,golang]
----
include::example$syntax.go[tag=hello]
----
<1> 单行导入
<2> 分组导入

== &sect; 常量

常量的声明与变量类似，只不过是使用 `const` 关键字。常量可以是字符、字符串、布尔值或数值。常量不能用 `:=` 语法声明。


.Example 2
[source,golang]
----
include::example$syntax.go[tag=const]
----
<1> 在 package 级的常量定义
<2> 数值常量是高精度的值。一个未指定类型的常量由上下文来决定其类型。

== &sect; for 语句

Go 只有一种循环结构：for 循环。

基本的 for 循环由三部分组成，它们用分号隔开：

. 初始化语句：在第一次迭代前执行
. 条件表达式：在每次迭代前求值
. 后置语句：在每次迭代的结尾执行

初始化语句通常为一句短变量声明，该变量声明仅在 `for` 语句的作用域中可见。一旦条件表达式的布尔值为 `false`，循环迭代就会终止。注意：和 `C`、`Java`、`JavaScript` 之类的语言不同，`Go` 的 `for` 语句后面的三个构成部分外没有小括号， 大括号 `{ }` 则是必须的。

.Example 3
[source,golang]
----
include::example$syntax.go[tag=for]
----

== &sect; if 语句

.Example 4
[source,golang]
----
include::example$syntax.go[tag=if]
----

== &sect; switch 语句

`switch` 是编写一连串 `if` - `else` 语句的简便方法。它运行第一个值等于条件表达式的 `case` 语句。

`Go` 的 `switch` 语句类似于 `C`、`C++`、`Java`、`JavaScript` 和 `PHP` 中的，不过 `Go` 只运行选定的 `case`，而非之后所有的 `case`。 实际上，`Go` 自动提供了在这些语言中每个 `case` 后面所需的 `break` 语句。 除非以 `fallthrough` 语句结束，否则分支会自动终止。 `Go` 的另一点重要的不同在于 `switch` 的 `case` 无需为常量，且取值不必为整数。

`switch` 的 `case` 语句从上到下顺次执行，直到匹配成功时停止。

.Example 5
[source,golang]
----
include::example$syntax.go[tag=switch]
----

== &sect; defer 语句

`defer` 语句会将函数推迟到外层函数返回之后执行。推迟调用的函数其参数会立即求值，但直到外层函数返回前该函数都不会被调用。

推迟的函数调用会被压入一个栈中。当外层函数返回时，被推迟的函数会按照后进先出的顺序调用。更多关于 `defer` 语句的信息，请阅读此博文。

.Example 6
[source,golang]
----
include::example$syntax.go[tag=defer]
----

== &sect; 指针

`Go` 拥有指针。指针保存了值的内存地址。与 `C` 不同，`Go` 没有指针运算。

.Example 7
[source,golang]
----
include::example$syntax.go[tag=pointer]
----

== &sect; 结构体

一个结构体（`struct`）就是一组字段（`field`）。结构体字段使用点号来访问。

结构体字段可以通过结构体指针来访问。如果我们有一个指向结构体的指针 p，那么可以通过 (*p).X 来访问其字段 X。不过这么写太啰嗦了，所以语言也允许我们使用隐式间接引用，直接写 p.X 就可以。

结构体文法通过直接列出字段的值来新分配一个结构体。使用 `Name:` 语法可以仅列出部分字段。（字段名的顺序无关）特殊的前缀 `&` 返回一个指向结构体的指针。

.Example 8
[source,golang]
----
include::example$syntax.go[tag=struct]
----

== &sect; 数组

类型 `[n]T` 表示拥有 `n` 个 `T` 类型的值的数组。数组的长度是其类型的一部分，因此数组不能改变大小。这看起来是个限制，不过没关系，Go 提供了更加便利的方式来使用数组。

.Example 9
[source,golang]
----
include::example$syntax.go[tag=array]
----
