= 基础语法

== &sect; Hello World

[source,golang]
----
include::example$basics.go[tag=hello]
----
<1> 每个 Go 程序都是由包构成的, 程序从 main 包开始运行
<2> 单行导入
<3> 分组导入

== &sect; 常量

[source,golang]
----
include::example$basics.go[tag=const]
----
<1> 包级的常量定义
<2> 数值常量是高精度的值。一个未指定类型的常量由上下文来决定其类型。

常量的声明与变量类似，只不过是使用 `const` 关键字。常量可以是字符、字符串、布尔值或数值。常量不能用 `:=` 语法声明。

== &sect; `for` 语句

`Go` 只有一种循环结构：`for` 循环。

.基本的 for 循环由三部分组成
[source,golang]
----
include::example$basics.go[tag=for-1]
----

它们用分号隔开：

. 初始化语句：在第一次迭代前执行
. 条件表达式：在每次迭代前求值
. 后置语句：在每次迭代的结尾执行

初始化语句通常为一句短变量声明，该变量声明仅在 `for` 语句的作用域中可见。一旦条件表达式的布尔值为 `false`，循环迭代就会终止。注意：和 `C`、`Java`、`JavaScript` 之类的语言不同，`Go` 的 `for` 语句后面的三个构成部分外没有小括号， 大括号 `{ }` 则是必须的。

.初始化语句和后置语句是可选的
[source,golang]
----
include::example$basics.go[tag=for-2]
----

.for 是 Go 中的 “while”
[source,golang]
----
include::example$basics.go[tag=for-3]
----

.无限循环
[source,golang]
----
include::example$basics.go[tag=for-4]
----
<1> 如果省略循环条件，该循环就不会结束。因此无限循环可以写得很紧凑
<2> 终止循环

== &sect; `if` 语句

.基础语法
[source,golang]
----
include::example$basics.go[tag=if-1]
----

.`if` 的简短语句
[source,golang]
----
include::example$basics.go[tag=if-2]
----

同 `for` 一样， `if` 语句可以在条件表达式前执行一个简单的语句。该语句声明的变量作用域仅在 if 之内。

.`if` 和 `else`
[source,golang]
----
include::example$basics.go[tag=if-3]
----

== &sect; switch 语句

.基础语法
[source,golang]
----
include::example$basics.go[tag=switch-1]
----
<1> 不退出 `switch` 语句，继续执行下一个 `case`

`switch` 是编写一连串 `if - else` 语句的简便方法。它运行第一个值等于条件表达式的 `case` 语句。

`Go` 的 `switch` 语句类似于 `C`、`C++`、`Java`、`JavaScript` 和 `PHP` 中的，不过 `Go` 只运行选定的 `case`，而非之后所有的 `case`。 实际上，`Go` 自动提供了在这些语言中每个 `case` 后面所需的 `break` 语句。 除非以 `fallthrough` 语句结束，否则分支会自动终止。 `Go` 的另一点重要的不同在于 `switch` 的 `case` 无需为常量，且取值不必为整数。

.没有条件的 `switch`
[source,golang]
----
include::example$basics.go[tag=switch-2]
----

没有条件的 `switch` 同 `switch true` 一样。这种形式能将一长串 `if-then-else` 写得更加清晰。

`switch` 的 `case` 语句从上到下顺次执行，直到匹配成功时停止。

== &sect; defer 语句

.基础语法
[source,golang]
----
include::example$basics.go[tag=defer]
----

`defer` 语句会将函数推迟到外层函数返回之后执行。推迟调用的函数其参数会立即求值，但直到外层函数返回前该函数都不会被调用。

推迟的函数调用会被压入一个栈中。当外层函数返回时，被推迟的函数会按照后进先出的顺序调用。更多关于 `defer` 语句的信息，请阅读此博文。
