= 基础语法

== &sect; Hello World

[source,golang]
----
include::example$basics.go[tag=hello]
----
<1> 每个 Go 程序都是由包构成的, 程序从 `main` 包开始运行
<2> 单行导入
<3> 分组导入

本程序通过导入路径 "fmt" 和 "math/rand" 来使用这两个包。

按照约定，包名与导入路径的最后一个元素一致。例如，"math/rand" 包中的源码均以 `package rand` 语句开始。

*注意：* 此程序的运行环境是固定的，因此 `rand.Intn` 总是会返回相同的数字。 （要得到不同的数字，需为生成器提供不同的种子数，参见 `rand.Seed`。 练习场中的时间为常量，因此你需要用其它的值作为种子数。）

此代码用圆括号组合了导入，这是“分组”形式的导入语句。当然你也可以编写多个导入语句，例如：

[source,golang]
----
import "time"
import "math/rand"
----

不过使用分组导入语句是更好的形式。

== &sect; 导出名

在 `Go` 中，如果一个名字以大写字母开头，那么它就是已导出的。例如，`Pizza` 就是个已导出名，`Pi` 也同样，它导出自 `math` 包。

`pizza` 和 `pi` 并未以大写字母开头，所以它们是未导出的。在导入一个包时，你只能引用其中已导出的名字。任何“未导出”的名字在该包外均无法访问。执行代码，观察错误输出。然后将 `math.pi` 改名为 `math.Pi` 再试着执行一次。

== &sect; 变量

.声明变量
[source,golang]
----
include::example$basics.go[tag=var-1]
----

`var` 语句用于声明一个变量列表，跟函数的参数列表一样，类型在最后。就像在这个例子中看到的一样，`var` 语句可以出现在包或函数级别。

.变量初始化
[source,golang]
----
include::example$basics.go[tag=var-2]
----

变量声明可以包含初始值，每个变量对应一个。如果初始化值已存在，则可以省略类型；变量会从初始值中获得类型。

.短变量声明
[source,golang]
----
include::example$basics.go[tag=var-3]
----

在函数中，简洁赋值语句 `:=` 可在类型明确的地方代替 `var` 声明。函数外的每个语句都必须以关键字开始（`var`, `func` 等等），因此 `:=` 结构不能在函数外使用。

.零值
[source,golang]
----
include::example$basics.go[tag=var-4]
----
<1> 数值类型为 0
<2> 布尔类型为 false
<3> 字符串为 ""（空字符串）

没有明确初始值的变量声明会被赋予它们的 零值。

.类型转换
[source,golang]
----
include::example$basics.go[tag=var-5]
----

表达式 `T(v)` 将值 `v` 转换为类型 `T`。与 `C` 不同的是，`Go` 在不同类型的项之间赋值时需要显式转换。试着移除例子中 `float64` 或 `uint` 的转换看看会发生什么。

.类型推导
[source,golang]
----
include::example$basics.go[tag=var-6]
----

在声明一个变量而不指定其类型时（即使用不带类型的 := 语法或 var = 表达式语法），变量的类型由右值推导得出。当右值声明了类型时，新变量的类型与其相同：

[source,golang]
----
var i int
j := i // j 也是一个 int
----

不过当右边包含未指明类型的数值常量时，新变量的类型就可能是 `int`, `float64` 或 `complex128` 了，这取决于常量的精度：

[source,golang]
----
i := 42           // int
f := 3.142        // float64
g := 0.867 + 0.5i // complex128
----

尝试修改示例代码中 `v` 的初始值，并观察它是如何影响类型的。

== &sect; 常量

[source,golang]
----
include::example$basics.go[tag=const]
----
<1> 包级的常量定义
<2> 数值常量是高精度的值。一个未指定类型的常量由上下文来决定其类型

常量的声明与变量类似，只不过是使用 `const` 关键字。常量可以是字符、字符串、布尔值或数值。常量不能用 `:=` 语法声明。

== &sect; `func` 关键字

.基础语法
[source,golang]
----
include::example$basics.go[tag=func-1]
----
<1> 函数可以返回任意数量的返回值，`swap` 函数返回了两个字符串
<2> 命名返回值
<3> 命名返回值也需要 `return`

`Go` 的返回值可被命名，它们会被视作定义在函数顶部的变量。返回值的名称应当具有一定的意义，它可以作为文档使用。没有参数的 `return` 语句返回已命名的返回值。也就是 直接 返回。直接返回语句应当仅用在下面这样的短函数中。在长的函数中它们会影响代码的可读性。

.函数值
[source,golang]
----
include::example$basics.go[tag=func-2]
----

函数也是值。它们可以像其它值一样传递。函数值可以用作函数的参数或返回值。

.函数的闭包
[source,golang]
----
include::example$basics.go[tag=func-3]
----

`Go` 函数可以是一个闭包。闭包是一个函数值，它引用了其函数体之外的变量。该函数可以访问并赋予其引用的变量的值，换句话说，该函数被这些变量“绑定”在一起。例如，函数 `adder` 返回一个闭包。每个闭包都被绑定在其各自的 `sum` 变量上。

== &sect; `for` 关键字

`Go` 只有一种循环结构：`for` 循环。

.基本的 for 循环由三部分组成
[source,golang]
----
include::example$basics.go[tag=for-1]
----

它们用分号隔开：

. 初始化语句：在第一次迭代前执行
. 条件表达式：在每次迭代前求值
. 后置语句：在每次迭代的结尾执行

初始化语句通常为一句短变量声明，该变量声明仅在 `for` 语句的作用域中可见。一旦条件表达式的布尔值为 `false`，循环迭代就会终止。注意：和 `C`、`Java`、`JavaScript` 之类的语言不同，`Go` 的 `for` 语句后面的三个构成部分外没有小括号， 大括号 `{ }` 则是必须的。

.初始化语句和后置语句是可选的
[source,golang]
----
include::example$basics.go[tag=for-2]
----

.for 是 Go 中的 “while”
[source,golang]
----
include::example$basics.go[tag=for-3]
----

.无限循环
[source,golang]
----
include::example$basics.go[tag=for-4]
----
<1> 如果省略循环条件，该循环就不会结束。因此无限循环可以写得很紧凑
<2> 终止循环

== &sect; `range`

.基础语法
[source,golang]
----
include::example$basics.go[tag=range]
----
<1> 若你只需要索引，忽略第二个变量即可

`for` 循环的 `range` 形式可遍历切片或映射。当使用 `for` 循环遍历切片时，每次迭代都会返回两个值。第一个值为当前元素的下标，第二个值为该下标所对应元素的一份副本。可以将下标或值赋予 `_` 来忽略它。

== &sect; `if` 关键字

.基础语法
[source,golang]
----
include::example$basics.go[tag=if-1]
----

.`if` 的简短语句
[source,golang]
----
include::example$basics.go[tag=if-2]
----

同 `for` 一样， `if` 语句可以在条件表达式前执行一个简单的语句。该语句声明的变量作用域仅在 if 之内。

.`if` 和 `else`
[source,golang]
----
include::example$basics.go[tag=if-3]
----

== &sect; `switch` 关键字

.基础语法
[source,golang]
----
include::example$basics.go[tag=switch-1]
----
<1> 不退出 `switch` 语句，继续执行下一个 `case`

`switch` 是编写一连串 `if - else` 语句的简便方法。它运行第一个值等于条件表达式的 `case` 语句。

`Go` 的 `switch` 语句类似于 `C`、`C++`、`Java`、`JavaScript` 和 `PHP` 中的，不过 `Go` 只运行选定的 `case`，而非之后所有的 `case`。 实际上，`Go` 自动提供了在这些语言中每个 `case` 后面所需的 `break` 语句。 除非以 `fallthrough` 语句结束，否则分支会自动终止。 `Go` 的另一点重要的不同在于 `switch` 的 `case` 无需为常量，且取值不必为整数。

.没有条件的 `switch`
[source,golang]
----
include::example$basics.go[tag=switch-2]
----

没有条件的 `switch` 同 `switch true` 一样。这种形式能将一长串 `if-then-else` 写得更加清晰。

`switch` 的 `case` 语句从上到下顺次执行，直到匹配成功时停止。

== &sect; `defer` 关键字

.基础语法
[source,golang]
----
include::example$basics.go[tag=defer]
----

`defer` 语句会将函数推迟到外层函数返回之后执行。推迟调用的函数其参数会立即求值，但直到外层函数返回前该函数都不会被调用。

推迟的函数调用会被压入一个栈中。当外层函数返回时，被推迟的函数会按照后进先出的顺序调用。更多关于 `defer` 语句的信息，请阅读此博文。
